name: moneroo_flutter_sdk
description: Moneroo SDK for Flutter. Integrate easily many payments solutions from Africa to the World.
version: 0.3.0
homepage: https://docs.moneroo.io
repository: https://github.com/moneroohq/moneroo_flutter
platforms:
  android:
  ios:
  web:

environment:
  sdk: "^3.3.0"
  flutter: ">=3.0.0"

dependencies:
  dio: ^5.4.1
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.0
  json_annotation: ^4.8.1
  url_launcher: ^6.2.5
  webview_flutter: ^4.7.0
  webview_flutter_android: ^4.3.2
  webview_flutter_wkwebview: ^3.13.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mocktail: ^1.0.3
  very_good_analysis: ^7.0.0
